unet:
  _class_name: UNet2DModel
  _diffusers_version: 0.28.2
  act_fn: silu
  add_attention: true
  attention_head_dim: 8
  attn_norm_num_groups: null
  block_out_channels:
    - 128
    - 256
    - 256
    - 256
  center_input_sample: false
  class_embed_type: null
  down_block_types:
    - DownBlock2D
    - DownBlock2D
    - DownBlock2D
    - DownBlock2D
  downsample_padding: 1
  downsample_type: conv
  dropout: 0.0
  flip_sin_to_cos: true
  freq_shift: 0
  in_channels: 4
  layers_per_block: 2
  mid_block_scale_factor: 1
  norm_eps: 1e-05
  norm_num_groups: 32
  num_class_embeds: null
  num_train_timesteps: null
  out_channels: 4
  resnet_time_scale_shift: scale_shift
  sample_size: 128
  time_embedding_type: positional
  up_block_types:
    - UpBlock2D
    - UpBlock2D
    - UpBlock2D
    - UpBlock2D
  upsample_type: conv

noise_scheduler:
  target: diffusers.EDMDPMSolverMultistepScheduler
  params:
    num_train_timesteps: 1000

loss_fn:
  target: losses.loss.EDMLoss
  params:
    sigma_data: 0.5

optimizer:
  betas:
    - 0.9
    - 0.999
  eps: 1e-08
  lr: 1e-4
  weight_decay: 1e-2

lr_scheduler:
  #name: cosine
  name: constant
  num_warmup_steps: 500
  num_cycles: 0.5
  power: 1.0

dataloader:
  data_dir: /scratch/kdur_root/kdur/shared_data/pdebench_data/2D/CFD/2D_Train_Rand/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5
  batch_size: 16
  num_workers: 0
  split_ratios: 
    - 0.8
    - 0.2
    - 0.0
  transform: normalize
  transform_args:
    mean: [0.0001482,  0.0000293, 5.0561895, 25.3754578]  
    std: [0.0422693, 0.0422711, 2.9536870, 22.0486488] 
    target_std: 0.5
  data_name: compressible_NS

accelerator:
  mixed_precision: fp16
  gradient_accumulation_steps: 1
  log_with: tensorboard

ema:
  use_ema: True
  offload_ema: False
  ema_max_decay: 0.9999
  ema_inv_gamma: 1.0
  ema_power: 0.75
  foreach: True

general:
  seed: 42
  num_epochs: null
  num_training_steps: 100000
  known_channels: [0,1,2,3]
  same_mask: True
  scale_lr: False
  output_dir: /scratch/kdur_root/kdur/ylzhuang/log/compressible_NS_uncond
  logging_dir: comp_NS
  tracker_project_name: compNS_tracker
  save_image_epochs: 5
  save_model_epochs: 50
  checkpointing_steps: 25000
  eval_batch_size: 8
  cond_drop_prob: null
  do_edm_style_training: True
  snr_gamma: null
  channel_names: ["Vx", "Vy", "pressure", "density"]