unet:
  _class_name: UNet2DModel
  _diffusers_version: 0.28.2
  act_fn: silu
  add_attention: true
  attention_head_dim: 8
  attn_norm_num_groups: null
  block_out_channels:
    - 128
    - 256
    - 256
  center_input_sample: false
  class_embed_type: null
  down_block_types:
    - DownBlock2D
    - AttnDownBlock2D
    - AttnDownBlock2D
  downsample_padding: 1
  downsample_type: conv
  dropout: 0.0
  flip_sin_to_cos: true
  freq_shift: 0
  in_channels: 4
  layers_per_block: 2
  mid_block_scale_factor: 1
  norm_eps: 1e-05
  norm_num_groups: 32
  num_class_embeds: null
  num_train_timesteps: null
  out_channels: 3
  resnet_time_scale_shift: scale_shift
  sample_size: 64
  time_embedding_type: positional
  up_block_types:
    - UpBlock2D
    - AttnUpBlock2D
    - AttnUpBlock2D
  upsample_type: conv

noise_scheduler:
  target: diffusers.EDMDPMSolverMultistepScheduler
  params:
    num_train_timesteps: 1000

loss_fn:
  target: losses.loss.EDMLoss
  params:
    sigma_data: 0.5

optimizer:
  betas:
    - 0.9
    - 0.999
  eps: 1e-08
  lr: 1e-4
  weight_decay: 1e-2

lr_scheduler:
  name: cosine
  num_warmup_steps: 500
  num_cycles: 0.5
  power: 1.0

dataloader:
  data_dir: /mnt/14ec0bc1-61ef-47a7-b0b0-623f4a658402/tonyz/data/shallow_water/uvh_unrolled.npy
  batch_size: 32
  num_workers: 8
  split_ratios: 
    - 0.8
    - 0.2
    - 0.0
  transform: normalize
  transform_args:
    mean: [0., 0., 1.0055307]  
    std: [0.0089056, 0.0089056, 0.0137398] 
    target_std: 0.5

accelerator:
  mixed_precision: fp16
  gradient_accumulation_steps: 1
  log_with: tensorboard

ema:
  use_ema: True
  offload_ema: False
  ema_max_decay: 0.9999
  ema_inv_gamma: 1.0
  ema_power: 0.75
  foreach: True

general:
  seed: 42
  num_epochs: 1000
  known_channels: [0, 1, 2]
  same_mask: True
  scale_lr: False
  output_dir: ./log/sw
  logging_dir: sw
  tracker_project_name: sw_tracker
  save_image_epochs: 1
  save_model_epochs: 10
  checkpointing_steps: 1000
  eval_batch_size: 8
  do_edm_style_training: True
  channel_names: ["u", "v", "h"]
  data_name: shallow_water